### ISSUE TITLE
V3 Looking for .ovr files

### ISSUE THREAD

**Issue by jlaura** [radiantearth/stac-browser#111]
I have a browser V3alpha6 instance running at: https://stac.astrogeology.usgs.gov/browser-dev/ for testing. The deploy has been smooth.

I am not getting COGs rendering and inspection of the network pane shows that the client is looking for <mycog.tif.ovr> files. I have overviews embedded as per the [GDAL docs](https://trac.osgeo.org/gdal/wiki/CloudOptimizedGeoTIFF) on building COGs.

Have I misconfigured something?

**Comment by m-mohr** [comment]
Great to hear deployment went smooth. STAC Browser itself doesn't have specific code for overviews. COGs and overviews are handled in a different library, but I'm not exactly sure where in the dependency tree (stac-layer > georaster-layer-for-leaflet > georaster > geotiff.js) this is implemented, I assume it's not stac-layer or georaster, but one of the other. Any hint where to (re-)open this issue, @DanielJDufour?

**Comment by DanielJDufour** [comment]
[georaster-layer-for-leaflet](https://github.com/geotiff/georaster-layer-for-leaflet) unfortunately doesn't currently support custom projections, but we should be able to get client-side rendering to work if we set the Leaflet Map's CRS to [Simple CRS](https://leafletjs.com/examples/crs-simple/crs-simple.html) like:
```js
const map = L.map("map", {
  crs: L.CRS.Simple
});
```

About the .ovr request, georaster automatically searches for a .ovr file because some image providers have had it as a separate file: https://github.com/GeoTIFF/georaster/blob/master/src/index.js#L89.  It shows as a network error, but shouldn't affect rendering.

Here's a little more on the custom projection issue:
I downloaded the geotiff at https://stac.astrogeology.usgs.gov/browser-dev/monoscopic/TC1S2B0_01_00293N743E0604/TC1S2B0_01_00293N743E0604.json and looked at the geokeys via:
```js
(await (await require("geotiff").fromFile("TC1S2B0_01_00293N743E0604.tiff")).getImage()).getGeoKeys()

{
  GTModelTypeGeoKey: 1,
  GTRasterTypeGeoKey: 1,
  GTCitationGeoKey: 'TransverseMercator MOON',
  GeographicTypeGeoKey: 32767,
  GeogCitationGeoKey: 'GCS Name = GCS_MOON|Datum = D_MOON|Ellipsoid = MOON|Primem = Reference_Meridian|',
  GeogGeodeticDatumGeoKey: 32767,
  GeogAngularUnitsGeoKey: 9102,
  GeogEllipsoidGeoKey: 32767,
  GeogSemiMajorAxisGeoKey: 1737400,
  GeogSemiMinorAxisGeoKey: 1737400,
  GeogPrimeMeridianLongGeoKey: 0,
  ProjectedCSTypeGeoKey: 32767,
  ProjectionGeoKey: 32767,
  ProjCoordTransGeoKey: 1,
  ProjLinearUnitsGeoKey: 9001,
  ProjNatOriginLongGeoKey: 63,
  ProjNatOriginLatGeoKey: 0,
  ProjFalseEastingGeoKey: 0,
  ProjFalseNorthingGeoKey: 0,
  ProjScaleAtNatOriginGeoKey: 1
}
```

The GeographicTypeGeoKey, ProjectedCSTypeGeoKey and ProjectionGeoKey set to 32767 indicates that the geotiff is using a custom projection.

We could check for this in stac-browser like:
```js
if (georaster.projection === 32767) {
    // set leaflet map's crs to Simple
} else {
   // carry on normally
}
``` 

It's really an issue with georaster-layer-for-leaflet but hopefully this workaround will work for you :-)

fwiw, this is what we use to get around issues rendering GeoTIFFs in the polar areas ([more info here](https://github.com/GeoTIFF/georaster-layer-for-leaflet/issues/47))

**Comment by m-mohr** [comment]
@jlaura Maybe I confuse something, but do I remember correctly that for non-Earth data you mentioned using 4326 as some kind of a workaround? I'm a bit confused by the 32767 code. Are there special codes you are using for non-Earth? Then we can probably implement Daniels workaround in stac-layer or so.

@DanielJDufour Thanks a lot! 👍

**Comment by DanielJDufour** [comment]
I should probably clarify that the projection code 32767 isn't something specific to USGS or non-Earth data.  It's just what GeoTIFF writers use to indicate a "user-defined" (custom) projection:
http://geotiff.maptools.org/spec/geotiff6.html#6.3.3.1

**Comment by m-mohr** [comment]
Ah, wasn't aware of that. Thought it's some kind of custom EPSG code or so. Then we could do that. Although is that really a problem right now, @jlaura?

**Comment by jlaura** [comment]
I'll take a look at the projection! Sorry for the noise re: OVRs. I also see the projection issue. Oddly, this works in stac-browser V2 (same data).

Is the tile server pulling the projection from the COG?

**Comment by m-mohr** [comment]
I assume that the tile server used for V2 is more capable (with regards to projections) than the client-side rendering library. You could enable the tile server again if you like, but we can also try to find a solution client-side, of course.

**Comment by jlaura** [comment]
@m-mohr That makes a ton of sense about what changed. I saw that option in the README and foolishly assumed it did not apply. 100% user error.  I'll look around a bit client side first since not needing a server side solution is preferable. Thanks @m-mohr  and @DanielJDufour  for the support on this!

**Comment by m-mohr** [comment]
Happy to help if there are any questions!

By the way, those .lbl and .pvl files, what are they? Looking at getting getter descriptions for various file types...

**Comment by jlaura** [comment]
They are image metadata, so plain text. I've been looking at the assets best practices in the STAC docs. I might need to add more descriptive roles for those to help. Our community is really familiar with those files, but that is not a reason to omit good descriptions. No reason for me to propagate these artificial barriers to entry for new users!
