### ISSUE TITLE
Catalog and collection showing icon or preview in list

### ISSUE THREAD

**Issue by chiarch84** [radiantearth/stac-browser#145]
It would be useful to have the possibility to show an image right next to the preview of a catalog or of a collection.

This could be done by looking at the existence of a **link with relation = "icon"** (since it is one of the available [rel types](https://www.iana.org/assignments/link-relations/link-relations.xhtml) ).

This way when the Catalog or Collection is shown in a list, an intuitive icon can be placed next to the title.

Here is an example of our catalog having sub-catalogs associated to "INSPIRE Themes".
![image](https://user-images.githubusercontent.com/98519154/162445576-53d5429e-aa93-4454-b9c4-166d15e78682.png)

At the moment it is not easy to understand at a glance which sub-catalog to open, but if I could place an icon next to the title it would look better and be more intuitive. 

Here an example:
![image](https://user-images.githubusercontent.com/98519154/162447692-ce334be6-2158-4c34-8014-362851598c1b.png)

The same would be useful for the list of collections. In that case we could look at links with **relation = "icon" or "thumbnail" or "preview"**  and show it right next to the collection, giving at a glance the idea of what the collection is.

**Comment by m-mohr** [comment]
The Browser already supports that. If there's a link with rel type preview or an asset with role thumbnail, it should show the image. Although this is meant more for like thumbnails of a nice visualization of the data, it should also show icons. We could probably also add something specifically for icons in the future, but maybe try whether the other approach also works for you.

**Comment by chiarch84** [comment]
I have many collections with "preview" link but I don't see any image next to the title in the collections list.

I haven't tried this yet for catalogs, but I will.

The only thing I can say is that when I put a preview image it is usually big enough to be seen in the collection or item description and is not going to be exactly the same thing that I would put as thumbnail or icon, in that case I might choose a more proper image. Plus, I might not want every single preview to be shown in the list (maybe because they're not nice and comprehensible enough), so if I have a specific type for it I would use it only if I want to show an icon in the preview of the collection or of the catalog.

I'm sorry but our STAC catalog is available only under authentication, so I'm afraid you can't test against it.

**Comment by m-mohr** [comment]
Could you copy an example of what your preview link looks like?

**Comment by m-mohr** [comment]
Has been implemented for catalogs, collections and items. If there's a link with relation type 'icon' included and a Browser-supported image media type given, the icon will be shown in the lists and also in the header of the page for the corresponding STAC entity. Please let me know what you think, @chiarch84.

**Comment by m-mohr** [comment]
Thanks for the feedback, will also discuss this with our UX expert. 

Thoughts @jsiarto ?

**Comment by m-mohr** [comment]
We've discussed this with @jsiarto and Travor. We have the issue that the left formatting is weird when there's a centered thumbnail. The left alignment would only be required for the non-standardized icons, otherwise, it works well centered. Items are also centered. Thus, we thought the only way out is to actually add the icons centered in a new line.

Technically, the icon is implemented in a component that is also used in places where it doesn't make sense to add a line break though. This is unfortunately one of the cases where a general-purpose tool like STAC Browser that tries to work for most cases can't cater for all cases. 

I've recently added a custom.scss for custom CSS declarations. The file is always wmepty so you can easily add CSS there without the risk to run into merge conflicts or so. Thus, I'd recommend to use this file to add custom CSS to left-align the corresponding boxes.

The following should help: 
```json
#stac-browser .card-columns .catalog-card {
	text-align: left !important;
	 .card-title {
		 text-align: left !important;
	}
}
```
