### ISSUE TITLE
Preview images don't appear anymore

### ISSUE THREAD

**Issue by chiarch84** [radiantearth/stac-browser#147]
I don't know if I'm doing something wrong, but since last week I can't see the "Preview" images anymore in Collections and Items pages. I only see the spatial extent but no image.
Until last deployment all my previews were correctly shown in a tab next to the spatial extent tab.

Now I get only the spatial extent:
![image](https://user-images.githubusercontent.com/98519154/162739360-385e0dec-bc53-41dd-bff7-bcef98861413.png)

**Comment by m-mohr** [comment]
For me they are still present, e.g. for MS PC: https://radiantearth.github.io/stac-browser/#/external/planetarycomputer.microsoft.com/api/stac/v1/collections/aster-l1t or for GEE: https://radiantearth.github.io/stac-browser/#/external/earthengine-stac.storage.googleapis.com/catalog/AAFC/AAFC_ACI.json

Could you provide an example JSON please so that I can reproduce the issue?

**Comment by chiarch84** [comment]
In my case I don't see the "Preview" button appear at all. But looking at your json I see as difference that you have `type:"image/png"` is this mandatory? I didn't have it before in any of my previews and they showed without any problem, but maybe now it is mandatory?

**Comment by m-mohr** [comment]
Hmm, yeah, I'd strongly recommend to add the media type to images as otherwise I can't really know what to expect. So if there's no media type, it could e.g. be a PNG or a plain Tiff for example. While the Browser can easily show a PNG and it works in this case, it would show a broken image in the Browser for a Tiff. Not sure what the default should be.

I could probably try to work around a bit by checking the file extension, but that's a workaround only. The ideal solution for clients is that a media type is present for links and assets (not only for images).

**Comment by m-mohr** [comment]
The recommendation is still to add a type field, but I've implemented the workaround mentioned above so thumbnails should usually still show up despite having no type assigned.
