### ISSUE TITLE
Projections convertion when not complying with the standard (epsg:4326)

### ISSUE THREAD

**Issue by vitornvpaixao** [radiantearth/stac-browser#156]
Imagine a STAC object where the values of `bbox` and `coordinates `do not comply with the standard, epsg:4326. This would make it impossible to initialise the polygons on the maps and consequently the images.

Does it make sense to implement a function/algorithm to convert any type of projection into the standard projection??

If so, what is the standard format or formats used in STAC objects (catalog, collection), to define the object projection? 

So far I've managed to find a consistent standard for items/features, since `proj:epsg` is set in the `properties` property. However, for the catalogue and collection it was not possible.

Thanks in advance

**Comment by m-mohr** [comment]
GeoJSON and all STAC entities (catalogs, collections, items) per specification must always be EPSG: 4326, otherwise it is invalid.
If you want to provide non EPSG:4326 projection geometry or bbox in Items, indeed you need to use the proj extension, but you still need to provide EPSG:4326 at the "top-level" in bbox and coordinates. For collections and catalogs you need to reproject your coordinates to EPSG:4326. 

As this is more a stac-spec issue rather than a STAC Browser issue, I'm closing here.
