### ISSUE TITLE
Resolve cloud storage URLs to HTTP for download purposes

### ISSUE THREAD

**Issue by mojodna** [radiantearth/stac-browser#2]
I.e. `s3://whatever/file` → `https://whatever.s3.amazonaws.com/file` (for publicly-accessible data).

Should we or shouldn't we (since we don't know permissions)? A `rel=alternate` (or `http` / `public` / something property on the link) equivalent might be a better mechanism, since it's explicit on the provider's part.

**Comment by lossyrob** [comment]
stac-browser is currently scoped to work with publicly accessible links. I say we should do the uri manipulation since we don't know permissions. I think the feature here would be to add support for reading from specific cloud providers via signed URLs, but that might be beyond the scope of the tool. Closing for now.
