### ISSUE TITLE
Assets with file path file:// show Unknown

### ISSUE THREAD

**Issue by chiarch84** [radiantearth/stac-browser#200]
![image](https://user-images.githubusercontent.com/98519154/177333508-6df06370-deaa-412f-a431-ab2a598079d9.png)

![image](https://user-images.githubusercontent.com/98519154/177333572-6287015a-6b98-46b1-9449-823e9123ec72.png)

It was probably introduced in  one of the last commits because this morning it didn't appear.

**Comment by m-mohr** [comment]
Which media type is this for?

**Comment by chiarch84** [comment]
application/x‐ogc-vrt

**Comment by m-mohr** [comment]
Hmm, could it be that you are using two different types of dashes here?
If I copy the media type into a unicode checker, it shows me that the first dasgh in `application/x‐ogc-vrt` is unicode character \u2010 isntead of a normal ASCII dash. That would be invalid and that's why the new and a bit more strict media type parser probably complains.

**Comment by chiarch84** [comment]
It might be! I'll test and let you know.
