### ISSUE TITLE
Only show json after refresh in subdirectories

### ISSUE THREAD

**Issue by MarcYin** [radiantearth/stac-browser#220]
I built the STAC browser with the version 3 beta 3. It works well if I navigate the pages by clicking different links, but it simply load the json file rather than the expected webpage after I refresh the page if I navigated into subdirectories.

Example:

1. works fine where I deploy the stac-browser:
https://gws-access.jasmin.ac.uk/public/nceo_ard/NCEO_ARD_STAC/
2. show json file only once I refresh the page:
https://gws-access.jasmin.ac.uk/public/nceo_ard/NCEO_ARD_STAC/UK-sentinel-2/collection.json

**Comment by m-mohr** [comment]
The way you want to deploy this does not work because the URLs are ambiguous, they are used both for the JSON files and the Browser and that can't work obviously. There are two way how you can resolve this:

1. Set `historyMode` to `hash` (see https://github.com/radiantearth/stac-browser/tree/dev#historymode ) then you get a slightly different URL to use for STAC Browser, but it removes the ambiguity. This is less good for SEO though and the URLs look a bit less nice.
2. You deploy STAC Browser to a folder with no additional content (especially no catalog files). Then you can work with the current historyMode (`history`), but you also need to configure your host to rewrite the requests correctly as defined in the docs, e.g. here: https://v3.router.vuejs.org/guide/essentials/history-mode.html#html5-history-mode

**Comment by MarcYin** [comment]
Thanks a lot for the instruction. I have moved the STAC browser to a new directory and configured the server `.htaccess` file with:

```
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_URI} !\.(ovr)$
 # exclude file with extension of .ovr 
 # source: https://stackoverflow.com/questions/4038079/rewriterule-in-htaccess-to-match-certain-file-extensions
  RewriteRule . /public/nceo_ard/NCEO_ARD/index.html [L]
 # STAC browser is deployed in  /public/nceo_ard/NCEO_ARD/ directory
</IfModule>
```
I do not fully understand how it works, but it serves the need...

Marc.
