### ISSUE TITLE
CORS detection should use OPTIONS pre-flight rather than relying on GET method

### ISSUE THREAD

**Issue by philvarner** [radiantearth/stac-browser#226]
While a GET request isn't required to preflight, one practical limitation is that an AWS REST API Gateway only allows configuration of the OPTIONS method for the CORS headers, so the initial GET request will not return the headers and the CORS error message appears. Always using an OPTIONS preflight for the initial request should solve this issue.

**Comment by m-mohr** [comment]
I'm using the default behaviors of browsers, I assume. At least I did not implement any special handling for CORS and as such it feels like that's not an issue in STAC Browser? Otherwise, do you have some documentation available around that issue? I am not using AWS and as such I also can't really test against it.

**Comment by philvarner** [comment]
this was my misunderstanding. the underlying problem was that the 401 response from the server that prompts auth was missing the CORS headers.
