### ISSUE TITLE
Usage of RFC 3339/ISO 8601 date format representation

### ISSUE THREAD

**Issue by jfbourgon** [radiantearth/stac-browser#228]
Dates present in HTML pages are displayed using Middle-endian date format (MM/DD/YYYY) which can represents ambiguity between Day and Month.
![image](https://user-images.githubusercontent.com/1030226/191306540-23f68e6d-084b-4b7c-b11d-cb8942ee194e.png)

ISO 8601 addresses the uncertainty around dates by setting out an internationally agreed way to represent dates: YYYY-MM-DD
For example, September 27, 2012 is represented as 2012-09-27

The recommendation is to use RFC 3339/ISO 8601 date format (YYYY-MM-DD) instead of Middle-endian date format (MM/DD/YYYY) in HTML pages in order to avoid ambiguity. Moreover the RFC 3339/ISO 8601 date format is the format used for datetime inside the STAC item specs: https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md#datetime.

**Comment by m-mohr** [comment]
RFC3339 is meant primarily for protocols, not for human consumption. STAC Browser itself is a UI for a machine-readable specification such as STAC. As such I'm trying to give a good experience also for not tech-savyy users by providing them with a date and time representation that they are used to, i.e. the one that they have selected specifically. So the settings used are coming from your system, so you've actually selected those in the Browser or OS at some point. For me, the German formats are used and they are less confusing. So if you think this format is not ideal you can change it in your settings. By the way, many users not so into tech are not aware of these standards at all and for them it is still unclear, because sometimes you also see YYYY-DD-MM in the wild.

**Comment by m-mohr** [comment]
One alternative for places where there is more space (like above) could be to give the month not as number but as word in the local representation, so e.g. something like Mar 22, 2022 or in German "22. März 2022".

**Comment by jfbourgon** [comment]
Thanks for the explanation. I didn't know that the web UI was relying on internal web browser settings to render dates according to selected Language instead of imposing a static format, which is a highly valuable approach. I confirm that changing the Language settings in the web browser impacts the way dates are rendered in the UI. No fix required then.

**Comment by rockliffelewis** [comment]
> STAC Browser itself is a UI for a machine-readable specification such as STAC. As such I'm trying to give a good experience also for not tech-savyy users by providing them with a date and time representation that they are used to, i.e. the one that they have selected specifically. The settings used in STAC Browser are coming from your system, you've selected those in the Browser or OS at some point. For me, the German formats are used and they are less confusing. So if you think this format is not ideal you can change it in your settings. By the way, many users not so into tech are not aware of these standards at all and for them it is still unclear, because sometimes you also see YYYY-DD-MM in the wild.

I understand the intent here and for most regions this approach is probably optimal, where it gets weird is in the English world where most people use the default browser setting of English (US), and so get the bizarre MM/DD/YYYY date format. In particular non-tech-savvy people won't know this setting even exists and will just complain that the date format is wrong.

Being able to set a date format for your instance of stac-browser would be useful in this case.

**Comment by m-mohr** [comment]
Please see the dedicated issue for this: #273 
Alternatively, you could also contribute a separate locale for your country: https://github.com/radiantearth/stac-browser#adding-a-new-language
