### ISSUE TITLE
Support for /queryables and /collections/collection-id/queryables endpoints

### ISSUE THREAD

**Issue by ycespb** [radiantearth/stac-browser#244]
We understand from issue #225 that the STAC-Browser may already provide support for additional queryables advertised via /queryables or /collections/collection-id/queryables.  We have patched our current implementation to test before committing to a full implementation at our end, but we don't manage to see advertised additional parameters appear ?  Is there something in particular that we missed (e.g. in the list of conformsTo ?) ?   Our endpoint is at https://radiantearth.github.io/stac-browser/#/external/eovoc.spacebel.be/.  We have added a /queryables endpoint also for https://radiantearth.github.io/stac-browser/#/external/eovoc.spacebel.be/collections/datasets.  PS: these parameters in the Queryables response are for the moment not working for real searches.  We plan to add a correct list (quite a bit of work) when the STAC-Browser can pick this information up, We assumed that they would show up next to an edit box with the parameter name, which is not the case. Difflicult to know what we did wrong .... Thanks in advance.

**Comment by m-mohr** [comment]
The first thing that I found is that the link to the queryables has the relation type `http://www.opengis.net/def/rel/ogc/1.0/queryables` instead of `queryables`, which seems to have changed recently. STAC Browser looks for the latter, I've fixed that.

The second thing is that STAC Browser currently only supports CQL Text, not CQL JSON. As such it looks for the CQL Text conformance class, which is missing from your implementation as far as I can see.

**Comment by ycespb** [comment]
Thanks for the very quick feedback.  We'll make the necessary changes at our end as well.

**Comment by m-mohr** [comment]
Let me know if you still have issues afterwards or if you have ideas how to improve the filters. It hasn't been tested a lot because only MS PC had a somewhat compliant implementation and no one else...

**Comment by ycespb** [comment]
We will certainly come back to you.  We are wondering whether the STAC-Browser will use enumeration information (lists of allowed values) and how queryables for collection search (API extension  for collection search) could be provided  also and found by STAC-Browser.  According to OGC API (Records), the /queryables andpoint would be for advertizing the collection search parameters (for the /collections endpoint) while the items search parameters would be under /collections/id/queryables.  STAC seems to have taken the /queryables also for item search parameters (causing a conflict).   We were also wondering whether without declaring CQL compliance or "filter", a queryables response could not be exploited by STAC-Browser  already for capturing parameters that allow "filtering on feature properties"  as in API Features Core:  https://docs.opengeospatial.org/is/17-069r4/17-069r4.html#_parameters_for_filtering_on_feature_properties.

**Comment by ycespb** [comment]
To explain my comment above:  all the additional parameters that our current API has are meant to be provided as individual HTTP query parameters.  This would be compatible with  https://docs.opengeospatial.org/is/17-069r4/17-069r4.html#_parameters_for_filtering_on_feature_properties.  However, to be able to enter them via the STAC-Browser, we understand that we need to implement an HTTP query parameter "filter" and all our existing parameters become part of the value of that parameter.  Thus instead of ?platform=proba&instrument=chris, we have to cope with ?filter="platform=proba AND instrument=chris" which requires us to extend our API (which we planned anyway to support CQL, but this will take some time).

**Comment by m-mohr** [comment]
STAC Browser supports enums. Collection Search is not implemented yet in STAC Browser, but it would be interesting to implement once the extension is a bit more stable (primarily looking at OGC API - Records here) and there's an implementation to test against.

STAC Browsers follows the Filter extension, which requires using the `filter` query parameter. It does not implement the Query extension as it is deprecated and does not support queryables. Without queryables a client can't provide a UI, so queryables support in Query would be the first step for support in STAC Browser. Similarly, for the "Parameters for filtering on feature properties" it seems I'd need to load the OpenAPI document to figure out what parameters are available, not the `/queryables` endpoint. OpenAPI parsing it out of scope for STAC Browser, I think, as it's otherwise not used at all in STAC specifications.

In principle I think the query generator can handle more encodings like Query and "Parameters for filtering on feature properties", but it needs to follow the specifications (I'm trying to avoid custom/proprietary code in STAC Browser) and this would need contributions from others, I don't have funding for it.

**Comment by ycespb** [comment]
(1) Thanks for the info.  There should be no need to read the OpenAPI definition to find the parameters as then the idea that these APIs simplify things goes out of the window.  I also agree that we should follow the specifications and no custom/proprietary stuff.  It is a matter of checking  large number of still not final/stable specification parts.    

 I see that the current OGC API Records draft spec still  allows to perform searches with HTTP request parameters ?prop=value and refers to /collections/{collection-id}/queryables for the list of "prop" (See bottom of the table 12 in this section:  https://docs.ogc.org/DRAFTS/20-004.html#_overview_4).  Is this something that could be supported  ? This would avoid having to implement the filter conformance class or the CQL conformance class and have additional search parameters like ?platform=proba&instrument=chris in my example above.  The STAC-Browser GUI does not really require changes for that (only restricting the operator to "=" ?

(2) I cannot find at the moment how OGC API-Records or API Common advertise queryables for collection search.  One interpretation that this is via the /queryables  endpoint, (also the assumption that is used in the Testbed-18 Engineering Report OGC 22-018) seems contradictied in other documents...  I'll keep you in the loop on this issue.

**Comment by m-mohr** [comment]
(1) Hmm... STAC API is built on top of OGC API - Feature and has no direct link to Records although alignment is aimed for. STAC Browser is primarily a STAC client, it won't be a OGC API - Records client. It would be easier to warrant implementation effort if there would be an extension built for STAC API that is based on this functionality Records. It would also help to define a conformance class for it, which seems to be missing right now? Without it will be hard for the client to detect whether it's supported or not.

(2) I guess opening an issue in OGC API - Records would help to clarify it and see what their intentions are. Could you do this? Happy to support it.

**Comment by ycespb** [comment]
(2) Sure: I opened the issue 196 on API Records referenced above.

**Comment by ycespb** [comment]
(1) Regarding the ?prop=value type of queries and the use of /queryables,  I opened an issue at https://github.com/opengeospatial/ogcapi-features/issues/778.
