### ISSUE TITLE
Support for STAC API collection-search extension

### ISSUE THREAD

**Issue by ycespb** [radiantearth/stac-browser#249]
@m-mohr, is it foreseen to support the STAC collection-search extension proposed at https://github.com/stac-api-extensions/collection-search and in particular the retrieval of collection search parameters from a Queryables response advertised via rel=".../queryables" in the /collections  response ?  We are eager to test this with our latest server implementation.

**Comment by ycespb** [comment]
Understood.  For point (1), I shared a temporary endpoint by email...  I understand the problem (2).

**Comment by ycespb** [comment]
To facilitate selecting the collection to be used for as item search on the normal search panel (https://radiantearth.github.io/stac-browser/#/search/external/eovoc.spacebel.be/), it would be helpful if there would be a way to reduce the number of collections listed in the listbox for instance by allowing to type a few characters to limit the visible entries to select from in the  listbox to the matching entries.   As there is separate functionality yet for collection-search, such improvement of the item search GUI would be very helpful for the case where there are hundreds of collections to choose from in the listbox (retrieved from /collections and following paging links) which will be the case in a future version of our server.

**Comment by m-mohr** [comment]
@ycespb Could you please open a new issue for this? Your request is mostly unrelated to implementing the collection search extension.

**Comment by ycespb** [comment]
Done.  #253 .

**Comment by chiarch84** [comment]
We are interested in the collection-search too. I think the actual STAC browser is really missing a way to find what the user needs when there are more collections. The item search is not the same because it returns too many results. Let's say I want to see all DEM collections available in a catalog, I don't want to end up with a list of thousands of items, I would just want to end up in a smaller list of all DEM collections and then I can myself go deeper in exploring the items of the collections I'm interested into.

**Comment by m-mohr** [comment]
@chiarch84 Could you provide an API implementation? Without an API implementation of said extension there won't be an implementation in STAC Browser, of course.

**Comment by chiarch84** [comment]
Well, we can add an endpoint to our APIs following the basics specs defined in https://github.com/stac-api-extensions/collection-search 

So we could have the following inupt parameters:
bbox
datetime
limit
text

But then I don't know how you would be able to test it since our APIs are behind authentication. You might register to our website maybe.

**Comment by m-mohr** [comment]
@chiarch84 There's an implementation of Collection Search (including free text search) in the collection-search branch. It would be great if you could test it against your implementation (please also note the recent changes in the collection search extension).

**Comment by chiarch84** [comment]
Sorry for the late answer @m-mohr 
We in fact do NOT have yet an implementation for collection-search. We're still working on it, so I cannot test your extension for now. Sorry.
