### ISSUE TITLE
Slimmed down production build

### ISSUE THREAD

**Issue by tschaub** [radiantearth/stac-browser#288]
I'm hoping to bundle STAC Browser in an executable and am looking for ways to trim the build size.  By default, `npm run build` generates 12MB of files.  I can get rid of 8.3MB of that by deleting the `*.map` files.  The `report.html` is another 500K.

I see that I can configure Vue to configure webpack to skip the sourcemaps in production mode:
```diff
--- a/vue.config.js
+++ b/vue.config.js
@@ -68,6 +68,8 @@ const config = {
 };
 
 if (process.env.NODE_ENV === 'production') {
+  config.configureWebpack.devtool = false;
+
   config.configureWebpack.plugins.push(new BundleAnalyzerPlugin({
     analyzerMode: 'static',
     openAnalyzer: false
```

But I imagine that others might want these sourcemaps.  Wondering if you have any other ideas for configuring things to get a smaller production build.

(As an aside, I'm not able to make any use of the sourcemap files – I see them in the debugger, but they are not useful for debugging – I'm new to Vue, so not sure what is expected here.)

**Comment by m-mohr** [comment]
I don't have a very good answer, but you already identified the biggest chunk, which is the source map files. I think we could indeed add the option to not generate source maps for production builds. The report.html should also not really be in the dist folder, I guess. But opening it may help you realize why the remaining files are so large. stac-layer and dependencies is already 1,7 MB in size. The only thing you could still remove are some language folders (from src/locales and config.js) if they are not needed. Thay may bring you down to 2,5 MB and then you likely hit the limits as long as stac-layers dependencies are so large.

**Comment by m-mohr** [comment]
I've added `config.configureWebpack.devtool = false;`, but after changing the path for the result.html it still appears in the dist folder so I just added a comment in the README that the file should not be deployed.

**Comment by tschaub** [comment]
Thanks, @m-mohr.  I also couldn't figure out how to make `vue-cli-service build` not generate the `report.html`.  It looks to me like the `--report` argument has no effect (I get the same result with and without it).

**Comment by tschaub** [comment]
Maybe I should have added that I think sourcemaps can be really valuable in production as well as during development (I have been glad to be able to debug production builds using them).  But it seemed to me like the sourcemaps generated by the `vue-cli-service build` command were not useful – meaning they didn't represent the actual source files and I couldn't really make use of them for debugging.  Maybe a webpack plugin is not correctly transforming them or maybe I was just not using them correctly.

In any case, I imagine someone may want to have good sourcemaps in production at some point and wonder why I suggested removing them.

**Comment by m-mohr** [comment]
The report was built by the BundleSizePlugin, but I updated the build process to not include it so that --report has an effect.

I've also added some additional scripts:
- `npm run build`: Compile the source code into deployable files for the web. The resulting files can be found in the folder `dist` and you can then deploy STAC Browser on a web host. There are two other variants:
  - `npm run build:report`: Same as above, but also generates a bundle size report (see `dist/report.html`), which should not be deployed.
  - `npm run build:minimal`: Same as above, but tries to generate a minimal version without bundle size report and without source maps.

We could add additional optimizations to `build:minimal`, but not sure yet what that could be. Open for suggestions.

**Comment by tschaub** [comment]
Nice.  The `build:minimal` script works well for me.  Thanks, @m-mohr.
