### ISSUE TITLE
Give more information why a given STAC Item isn't valid.

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-browser#307]
It's awesome that stac-browser validates items, but if it's not valid I just see a big 'X': 

<img width="1080" alt="Screenshot 2023-04-19 at 8 58 46 PM" src="https://user-images.githubusercontent.com/407017/233254689-d13aea10-3c4a-40f2-b017-121531070ae7.png">

I'd like to tell that provider why their STAC Item isn't valid, but I'm not sure what's wrong. Item is at https://radiantearth.github.io/stac-browser/#/external/s3.us-west-2.amazonaws.com/umbra-open-data-catalog/stac/2023/2023-04/2023-04-11/25df597f-c90b-47d5-bce1-fdb68090d577/25df597f-c90b-47d5-bce1-fdb68090d577.json?.asset=asset-GEC

**Comment by m-mohr** [comment]
Yeah, I had hoped to integrate this better with staclint.com (which currently is used in the background).
I asked them to provide an interface for it so that I can link to it directly, but that never happened so I need to find another solution. I hope to be able to split stac-node-validator into parts so that I can use this as validation engine directly, but didn't had the time for it yet.

**Comment by m-mohr** [comment]
![grafik](https://github.com/radiantearth/stac-browser/assets/8262166/20feab2b-3434-4358-93f2-8531ec6b15db)
