### ISSUE TITLE
weird display issues with Umbra's open data catalog

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-browser#308]
When I go to [Umbra open data in stac browser](https://radiantearth.github.io/stac-browser/#/external/s3.us-west-2.amazonaws.com/umbra-open-data-catalog/stac/catalog.json?.language=en) I get some weird errors on most all the items. See like: 

<img width="824" alt="Screenshot 2023-04-19 at 9 02 24 PM" src="https://user-images.githubusercontent.com/407017/233255110-81d0c27b-6565-4c07-add4-b9ff36980238.png">

It's at [this item](https://radiantearth.github.io/stac-browser/#/external/s3.us-west-2.amazonaws.com/umbra-open-data-catalog/stac/2023/2023-04/2023-04-01/fc889f60-1e9f-45d4-8b8a-0db999e8a6cc/fc889f60-1e9f-45d4-8b8a-0db999e8a6cc.json) - the rendered image is a small square, outside of the bounding box. If I load the cog [elsewhere](https://www.cogeo.org/map/#/url/https%3A%2F%2Fumbra-open-data-catalog.s3.amazonaws.com%2Fsar-data%2Ftasks%2Fad%2520hoc%2FFallon%2520Station%2C%2520Nevada%2F2716e35a-57a0-4732-8e0a-eb406f9062b7%2F2023-04-01-04-46-21_UMBRA-04%2F2023-04-01-04-46-21_UMBRA-04_GEC.tif/center/-118.6265,39.3959/zoom/14) then it matches the bounding box. 

Just about every one I've tried (maybe 6 or 7?) seems to have this problem. Except one, that does not display on the map and raises an error about invalid lat/long:
https://radiantearth.github.io/stac-browser/#/external/s3.us-west-2.amazonaws.com/umbra-open-data-catalog/stac/2023/2023-04/2023-04-16/ac3c40b6-b517-4661-8039-b1437dd91c56/ac3c40b6-b517-4661-8039-b1437dd91c56.json?.asset=asset-GEC

Note that none of the stac items seem to validate, and I'm happy to go tell them to fix their items (though I'm not sure exactly what the problem is) - but since COG's displayed normally elsewhere it seemed like an issue with stac browser.

**Comment by p1d1d1** [comment]
Most of the items have issues, e.g.:

- they are missing the bbox property
- view:azimuth cannot be negative
- sar:looks_range has to be an int

In case you can debug, e.g., with: https://staclint.com/

**Comment by m-mohr** [comment]
Moved to https://github.com/stac-utils/stac-layer/issues/61

**Comment by CloudNiner** [comment]
Hi all -- Andy from Umbra here. We just deployed a fix for the invalid STAC Items, the catalog now validates against STAC 1.0.0 with pystac:

<img width="1174" alt="Screenshot 2023-08-30 at 8 18 41 PM" src="https://github.com/radiantearth/stac-browser/assets/1818302/538ecadb-9793-4539-8a0a-d20152012419">

Apologies for the delay in fixing the validation!

Perhaps this issue can be closed since the rendering issue was moved over to `stac-layer`?

**Comment by CloudNiner** [comment]
Hi all -- Andy from Umbra here. We just deployed a fix for the invalid STAC Items, the catalog now validates against STAC 1.0.0 with pystac:

<img width="1174" alt="Screenshot 2023-08-30 at 8 18 41 PM" src="https://github.com/radiantearth/stac-browser/assets/1818302/538ecadb-9793-4539-8a0a-d20152012419">

Apologies for the delay in fixing the validation!

Perhaps this issue can be closed since the rendering issue was moved over to `stac-layer`?
