### ISSUE TITLE
catalog doesn't equal collection

### ISSUE THREAD

**Issue by rbavery** [radiantearth/stac-browser#348]
https://github.com/carpentries-incubator/geospatial-python/issues/143

I think catalog should be renamed to collection. For example, Earth Search v1 has 7 collections, and it is one catalog containing those collections, but stac-browser says there are 7 catalogs.

https://radiantearth.github.io/stac-browser/#/external/earth-search.aws.element84.com/v1/?.language=en

**Comment by m-mohr** [comment]
This is intentional. STAC Browser is also meant for "novice" users, meant to use not too technical terminology and make navigation for users easy. As such it merges Catalogs and Collections, the difference between them is often not even clear to technical users. Catalog (explicitly not "STAC Catalog") is a generic term that is commonly understood and as such that's used.
