### ISSUE TITLE
item properties titles

### ISSUE THREAD

**Issue by sbrunato** [radiantearth/stac-browser#35]
Hi, would it be possible to load item properties titles from extension schema ?
For the moment they are stored statically in https://github.com/radiantearth/stac-browser/blob/master/src/properties.js
Reading the titles from extensions schemas would allow to display properties titles for new/vendor extensions

**Comment by m-mohr** [comment]
Just a note from my side: Several of the schemas don't have titles and parsing the titles from the Schema is likely prone to errors for more complex schemas, so I'm not sure how well that would work, but in principle this is a good idea as the properties will be outdated regularly.

**Comment by m-mohr** [comment]
I'll make a separate package that  includes details on how to render field information in web environments (e.g. STAC Browser, openEO vue components, ...). This will be a small library that has the field titles with additional metadata and helpers like unit, prefix, suffix, formatters etc. The list will be based on the JSON Schemas, but will not directly use them due to the fact that we (1) don't want to load them to avoid large bundles/load too many files and (2) can't be sure we can actually read titles (for more complex schemas).

**Comment by m-mohr** [comment]
I have implemented a package called stad-fields, which contains a fields.json where metadata about fields can be stored and retrieved from. Happy to accept PRs to add new fields: https://github.com/stac-utils/stac-fields
This new package is now used to render fields in STAC Browser. To not make STAC Browser to heavy-weight, I'll not implement a JSON Schema based resolver.
