### ISSUE TITLE
Pagination buttons don't update after clicking "Next"

### ISSUE THREAD

**Issue by christophfriedrich** [radiantearth/stac-browser#426]
I'm using version 3.2.0-beta.1 at https://radiantearth.github.io/stac-browser/

I made a search request returning 14 items:

> ![grafik](https://github.com/radiantearth/stac-browser/assets/17781682/d747bcde-a671-4f8e-b3cb-66c045e4bae0)

Here's the request, although I doubt it's specific to this query: POST https://earth-search.aws.element84.com/v1/search with `{"datetime":"2024-03-04T20:00:00.000Z/2024-03-22T20:00:00.000Z","bbox":[13.171234130859377,53.81200414120256,13.274230957031252,53.85252660044951],"limit":12,"collections":["sentinel-2-c1-l2a"]}`

Those 14 items are paginated into pages of 12 items each, so initially the previous/next buttons perfectly look like this:

> ![grafik](https://github.com/radiantearth/stac-browser/assets/17781682/e5fe0881-b140-4d16-a02a-4e019342de7b)

But after clicking on "Next", the buttons stay the same:

> ![grafik](https://github.com/radiantearth/stac-browser/assets/17781682/c19cdc37-4cde-4c87-8c59-611ea852b260)

So that I can't go back to the previous page. To reach there, I have to re-submit the search, which at least works.

But I _can_ go forward _again_, leading to this state:

> ![grafik](https://github.com/radiantearth/stac-browser/assets/17781682/18fb01e7-8e8f-494f-9d18-07fff7b1e727)

**Comment by christophfriedrich** [comment]
While searching in a neighbouring area where the result included only 7 matches, I spotted that the "Next" button remains active even when there is no second page at all:

> ![grafik](https://github.com/radiantearth/stac-browser/assets/17781682/0a977018-ce73-46f1-b302-a02620f8a604)

**Comment by m-mohr** [comment]
Thanks for the report.
- The previous link is not working because the API doesn't provide a "prev" or "previous" link in their response.
- Similarly, the API the API does provide a next link although the next page returns no results.

I'm closing here because it's an API issue, which should be reported to Earth Search directly.
@matthewhanson @philvarner fyi

**Comment by philvarner** [comment]
I think this should be reopened.

Earth Search does not provide a `prev` link because the database does not support that form of pagination (at least easily and robustly), but the `prev` link is optional for pagination. I think stac-browser should conditionally show the Previous button only if there is a `prev` link in the response.

As for the issue with Next, pagination will typically result in an empty last page, since the server code doesn't know that it has paginated through all of the results until it gets an empty result set from the database. I think this could be made more clear in stac-browser, since the last page displays the "no results were found for this filter" rather than a message that is more specific to pagination, e.g., "no more results available".
