### ISSUE TITLE
How to integrate a zarr component into stac-browser

### ISSUE THREAD

**Issue by rabernat** [radiantearth/stac-browser#44]
We are working on referencing Zarr stores as collection-level assets from STAC catalogs (see https://github.com/radiantearth/stac-spec/issues/781 for discussion). We will basically point to a `.zmetadata` json file which represents the zarr ["consolidated metadata"](https://zarr.readthedocs.io/en/stable/tutorial.html#consolidating-metadata) for the store. Here is an example of what this file looks like: https://storage.googleapis.com/cmip6/tracmip/A3hr/aqua4xCO2/AM21/hus/v20190116/.zmetadata

Now we would like to figure out how to render some of this metadata in stac browser. I hacked together some vue components for doing this from a single zarr store here: https://github.com/rabernat/zarr-metadata-vue-browser; but I am very far from a competent vue developer.

*Can you provide some guidance on the overall architecture for integrating a custom collection-level asset viewer into a stac browser?* 

cc @charlesbluca @jhamman

**Comment by lossyrob** [comment]
Hi @rabernat - looks like a lot of great work is happening to get zarr and STAC working together! It looks like what you need is #38 to be implemented, and then a way to render the zarr metadata explicitly.

I ran the zarr-metadata-vue-browser agains the test .zmetadata you mentioned in this issue, and I think is a good starting point for adding metadata to the stac-browser if there's a collection-level asset that is a zarr file.

My first guess at the way to implement this is to have a computer property on the `Catalog` (e.g. [like for providers](https://github.com/radiantearth/stac-browser/blob/master/src/components/common.js#L81)component that would read and return the zarr metadata asset information if it was available, and then similar to how something like [providers are rendered](https://github.com/radiantearth/stac-browser/blob/master/src/components/Catalog.vue#L175) render the zarr components for each zarr metadata that exists. It might be tricky to contain that all in the sidebar information, so perhaps this info would deserve it's own tab.

What is the way zarr metadata is being specified as a collection asset? Will it have a specific `media_type`? That's how we determine what assets can show up on a map as a COG - [by checking the media type of assets](https://github.com/radiantearth/stac-browser/blob/master/src/components/Item.vue#L419).

**Comment by rabernat** [comment]
> What is the way zarr metadata is being specified as a collection asset? Will it have a specific `media_type`?

This is what @charlesbluca and I are working on in https://github.com/pangeo-data/pangeo-datastore-stac/issues/4. I think the `.zmetadata` file will be an asset with `media_type='application/json'`. We are open to advice on the proper `role`. I guess `metadata`? Can we also have a special `role` for `zarr-consolidated-metadata`/

**Comment by lossyrob** [comment]
@rabernat makes sense - for the stac-browser case, it would be easiest to pick out the zarr metadata if the `role` was specific to `zarr`. However the logic could also easily look for assets with the `metadata` role that had a `.zmetadata` extension, so I think whatever is decided that's best for the spec will work as long as the metadata can differentiated somehow.

**Comment by rabernat** [comment]
In https://github.com/pangeo-data/pangeo-datastore-stac/pull/6, @charlesbluca added the assets. They look like this

```json
  "assets": {
    "zmetadata": {
      "href": "https://storage.googleapis.com/pangeo-ecco-sose/.zmetadata",
      "description": "Consolidated metadata file for Zarr store",
      "type": "application/json",
      "roles": [
        "metadata",
        "zarr-consolidated-metadata"
      ]
    }
  }
```
https://github.com/pangeo-data/pangeo-datastore-stac/blob/c8044d7b30590353a4a2b8903a7ae190df9a27a5/master/ocean/SOSE/collection.json#L70-L80


> My first guess at the way to implement this is to have a computer property on the `Catalog`

So would a PR to implement this in stac-browser be our next step? This sounds like a concrete action we could work on.

> It might be tricky to contain that all in the sidebar information, so perhaps this info would deserve it's own tab.

:+1: There is a ton of info in the zarr metadata!

**Comment by lossyrob** [comment]
Thanks for the description of the roles - that makes sense and should be easy to identify in stac-browser.

> So would a PR to implement this in stac-browser be our next step? 

A PR would be awesome! Please let me know how I can be helpful navigating the codebase or thinking through any challenges you face while working through it.

**Comment by charlesbluca** [comment]
Thanks for your help in moving this forward @lossyrob! A couple questions:

- Should the GET request for the Zarr metadata file be done within the computed property (in [common.js](https://github.com/radiantearth/stac-browser/blob/master/src/components/common.js)), or within the Vue component it's rendered in using the `mounted` hook?
- Looking into #47, would the collection summaries tab be a good place to hold the rendered Zarr metadata, or would it be better to give it its own separate tab?

**Comment by lossyrob** [comment]
@charlesbluca I'm actually going to move the summary metadata to the right bar per [Matthias's suggestion](https://github.com/radiantearth/stac-browser/pull/47#issuecomment-696210448), as I agree that's a more proper place for summary properties since they more closely match the metadata being displayed in the sidebar.

However the Zarr metadata is specific enough that I think having its own tab makes sense, so I'd suggest repeating the tab approach I took in #47 but for a Zarr-specific tab.

For the GET request question - IMO common.js is overloaded at this point, and as much as we can keep things out of it and in it's own components the better. Fetching in the component as you mentioned would be the better approach to me.

**Comment by charlesbluca** [comment]
Thanks for the suggestions! Your tab approach in the PR should be a great help in getting this implemented - this shouldn't be too far off from @rabernat's initial example.

**Comment by charlesbluca** [comment]
Now that #57 is merged, we have a ZarrMetadataTab component to render a `zarr-consolidated-metadata` asset if it exists within a Collection. Some other places we would like to expand upon this:

- Versioned Zarr metadata assets, along with a check in the component's parsing function to account for version
- Adding styling to make the component's design more cohesive with that of STAC Browser (either independently or in a future sprint)
- Resolving CORS/requester pays conflicts with Zarr datasets in our [STAC catalogs](https://github.com/pangeo-data/pangeo-datastore-stac), so that the contained datasets can be rendered in STAC Index

I'm happy to discuss more ideas about where to go from here, although I'd imagine that might be better fit for a new issue.

**Comment by m-mohr** [comment]
Agreed. Feel free to create new issues. I'm closing here to keep the issues "clean". Thanks for your contribution to STAC.
