### ISSUE TITLE
Supporting CQL Advanced Operators

### ISSUE THREAD

**Issue by mngspb** [radiantearth/stac-browser#495]
Hi Matthias,

I noticed that CQL advanced operators (e.g.: LIKE) has been supported since the version 3.0.1. I'm using STAC Browser (https://radiantearth.github.io/stac-browser) version 3.2.0 to point to a STAC API that is supporting CQL advanced operators BUT the LIKE operator is not shown in the “additional filters” section.

Could you tell me how to get the LIKE operator (and BEWTEEN, IN operators) shown?

Thank in advance,
Minh

**Comment by drnextgis** [comment]
I've encountered the same issue. Since we are using `stac-fastapi` as our STAC server, we're getting the value defined [here](https://github.com/stac-utils/stac-fastapi/blob/4491fa1ee384cd3e789e30aaa1252cdbb2ea3246/stac_fastapi/extensions/stac_fastapi/extensions/core/filter/filter.py#L38C10-L38C81). Additionally, the OGC [standard](https://docs.ogc.org/is/21-065r2/21-065r2.html#_conformance_class_advanced_comparison_operators) specifies the reference URI as:

```
http://www.opengis.net/spec/cql2/1.0/conf/advanced-comparison-operators`
```

**Comment by drnextgis** [comment]
@m-mohr are the changes already available on https://radiantearth.github.io/stac-browser? 
I don't see any changes with our private STAC API instance.

Also the current dropdown appears like this, with the third item hidden behind the sort input.
![image](https://github.com/user-attachments/assets/071847ef-7626-41d8-8cb9-1754813dbb06)
