### ISSUE TITLE
Navigating to "related" collections/catalogs

### ISSUE THREAD

**Issue by ycespb** [radiantearth/stac-browser#50]
The STAC collection spec defines some relations that are meant to refer to other STAC collections via their URL (e.g. rel="derived_from").  Could STAC browser allow visualising/hyperlinking to some of these relations (if the rel-type is configured to be shown), and possibly support a more general relation such as rel="related" (with type="application/json") ?  Uses cases are to refer to catalogs with data from other instruments for the same platform, or same instrument in a different mode or catalogs/collections for the same platform from other organisations etc..

**Comment by lossyrob** [comment]
One idea to handle this generally is to have a "Links" tab for each of Catalog, Collection and Items that renders any link that isn't being handled by some other Tab or visualization (e.g. the breadcrumbs for "parent" and the items tab for "item"). That way the link rels you mention would be on that tab, with a clickable HTML link.

We could define a subset of rels (e.g. derived_from) that, if the HREF shares a root with the stac-browser's CATALOG_URL, would link to a stac-browser page for that STAC object rather than directly to the JSON STAC file.

Does that sound like a reasonable solution to the use cases you have?

**Comment by ycespb** [comment]
@lossyrob seems like a nice solution to me.

**Comment by emmanuelmathot** [comment]
Great solution. Indeed, in my application, I have many "related" (rel="related") items between each others and I'd like to navigate easily from one to another. The view should also include the title and the type when available. Thx!

**Comment by m-mohr** [comment]
Could this fail with STAC Browsers that are pre-rendered? In general I think this could be a source of bugs if you switch between catalogs with a single STAC Browser instance... (slug generation? cache conflicts?) Not sure, but something that needs good testing, I assume...

**Comment by m-mohr** [comment]
@emmanuelmathot @ycespb I'm planning to work on this in the next months. It would help me if you could provide some links to items/catalogs/... that would benefit from this feature so that I have something to test against.

**Comment by ycespb** [comment]
@m-mohr Hi Matthias, we will put in place an example and get back to you when it is available.  Our intention is to add a link to a catalog/collection representing an instrument such as https://ergo.spacebel.be/concepts/instruments/chris  and allow navigation to the catalogue representing the platform, in this case https://ergo.spacebel.be/series/eo%3Aplatform/PROBA-1.  We assume we can add a link in the CHRIS (instrument) collection like this :
`  {
      "rel": "related",
      "href": "https://ergo.spacebel.be/series/eo:platform/PROBA-1",
      "type": "application/json"
    },`

**Comment by m-mohr** [comment]
That sounds good, but I'm just wondering whether the relation type is actually specified in stac-spec? I can't find it so for a client it would be a stretch to assume that a rel type related with a json content type would lead to a STAC entity. So if there's no such thing in the spec yet, we should probably add it.

**Comment by ycespb** [comment]
@m-mohr , would you have a different relation in mind for this ?  I wonder if the client could not decide based on the media type used in the link (independent of the actual relation) to understand whether it represents a link to a different STAC collection or catalogue is meant and "display" the relation-name and/or the link label ?  Is there a better/more precise media type defined for a STAC catalog/collection to be used instead ?  we use a media type like this for the moment: `"type": "application/geo+json;profile=\"https://stacspec.org\""` for geoJSON Features or FeatureCollections using STAC conventions;..

**Comment by m-mohr** [comment]
No, related sounds alright. We just should specify in stac-spec that "related" with the corresponding media types for Items/Catalogs/Collections should be only used for STAC. If we want to make it 100% clear, we could just propose a new rel type, e.g. `related-item` / `related-catalog` or so. ;-)

We can't change the media types, unfortunately (IANA doesn't allow it to be registered).

**Comment by ycespb** [comment]
@m-mohr but the "profile" extension can be added to the media type as done in the JSON-LD specification which uses the same approach;  See https://www.w3.org/TR/json-ld11/#iana-considerations

**Comment by m-mohr** [comment]
As we can't register it, we can't put it in the spec. See https://github.com/radiantearth/stac-spec/issues/851 for details.

**Comment by m-mohr** [comment]
Looks good to me, thanks.

**Comment by m-mohr** [comment]
This has been implemented in STAC Browser 3 for the relation types related, derived_from and canonical.

**Comment by chiarch84** [comment]
Hi all, we're implementing the STAC Browser version 3 for our EO Catalog and I found this issue that might be improved further. 

There are other link types described in the [version STAC extension](https://github.com/stac-extensions/version) such as "latest-version" and "successor-version" that it would be good to be able to resolve in case they are relative links.

Could it be possible to have the same "resolving" mechanism also for these type of relative links? Since at the moment only our "related" relative links work, while the other types fail resolving.

**Comment by m-mohr** [comment]
Sure, that's a good idea. I'll implement this in the next few days. Are there any other link relation types that should be resolved that way?

**Comment by chiarch84** [comment]
Great! I guess also "predecessor-version"

**Comment by m-mohr** [comment]
Yes, I was more thinking about other extensions defining similar link rel types or so...

**Comment by chiarch84** [comment]
Well, concerning these links I think it would be great to have their "title" as the name of the link (as done for the items for example). 

And concerning  "latest-version" and "successor-version" and  "predecessor-version" it would be useful to have them showed underneath the "deprecated" box. So that the user can at a glance see that a newer version exists.

**Comment by m-mohr** [comment]
Good ideas! I like those. Will check how I can make this work best.

**Comment by chiarch84** [comment]
By thinking a little more about it I believe that also the "relation" relative links should be shown in a different way.

Just suggesting some ideas.

At the moment there is no distinction between links to "external" resources (such as other web pages or other) and "internal" ones (relative links). 

The related collections or items in the same catalog could have a specific title such as "Related resources in the Catalog" or something similar. Because many times the users want to directly jump to similar resources available in the same catalog.

**Comment by m-mohr** [comment]
The three relation types defined in the version extension are now "internal" links to other STAC Browser pages if the media type doesn't fit.

Latest and if available the successor versions are now shown in the deprecation note:
![grafik](https://user-images.githubusercontent.com/8262166/151709551-ff3ce3cd-fbd5-4742-a24e-21939f17a83f.png)
The link title will be shown. If no title is present it will default to "Go to <latest|successor> version".

All links to prev/next/latest version are still shown in the "Additional resources" list.

All external links now get a small "external link" icon (which is https://icons.getbootstrap.com/icons/box-arrow-up-right/) appended so that internal and external links can be distinguished more easily. Otherwise, there's no different grouping yet as they are relatively prominently shown anyway and I would not really know where to put them to give them even higher visibility.

Let me know how you like it, please!

**Comment by chiarch84** [comment]
Seems much clearer now! Thanks! Though I can't really find a working example in the Demo. I tried the Google Earth catalog that has a lot of deprecated collections, but the links don't seem to work. Good also to have a way to distinguish internal and external.

**Comment by m-mohr** [comment]
I had hoped you'd have a demo because you were asking for it. ;-)
Indeed, not a lot of catalog use the link relation types so I doubt there will be a live demo. I made one up for development purposes locally...

**Comment by chiarch84** [comment]
Yes we do use a non public demo by taking STAC Browser v3, but not updated every day with all changes.
I thought though that this catalog was updated with all changes: https://radiantearth.github.io/stac-browser/ isn't it?

For example in the google catalog I can already see this last development you created: https://radiantearth.github.io/stac-browser/#/external/earthengine-stac.storage.googleapis.com/catalog/LANDSAT_LT4_L1T_TOA.json The only problem is that the link doesn't work.

**Comment by m-mohr** [comment]
Yes, although I meant a STAC catalog. But you found one for GEE and it's working there:
![image](https://user-images.githubusercontent.com/8262166/151784508-f9999e2c-79f8-4f4a-b9ad-a3934903eaec.png)

The link to the latest version of course is not ideally titled, but that's an issue of the underlying catalog...

**Comment by chiarch84** [comment]
Yes we do have a STAC catalog too. I just checked your updates in our catalog now!
The next and latest version work perfect!
The link added to the externals is a good idea too. 
The only part that doesn't convince me too much are the related ones with the word "related" in front. But for the moment I don't have better ideas so it is good like this! Thanks a lot for the improvement.

**Comment by m-mohr** [comment]
Great to hear. 

You should probably provide a better title for the links in the catalog then.
If the browser only gets a rel type and a URL, there's not much the Browser can to do create a meaningful title tbh.

**Comment by ycespb** [comment]
@m-mohr , we also have "related" links to link (local) catalogs representing a mission to the catalogue for an instrument.  Example is at https://eovoc.spacebel.be/concepts/instruments/chris (part of the FedEO Clearinghouse catalogue in StacIndex - publicly accessible).  We are looking forward to see your support for such links in STACBROWSER.

**Comment by m-mohr** [comment]
@ycespb Yes, I have used FedEO for testing purposes. The functionality is already present in the current alpha version of STAC Browser v3.

**Comment by simonff** [comment]
> Yes, although I meant a STAC catalog. But you found one for GEE and it's working there: ![image](https://user-images.githubusercontent.com/8262166/151784508-f9999e2c-79f8-4f4a-b9ad-a3934903eaec.png)
> 
> The link to the latest version (LANDSAT...) of course is not ideally titled, but that's an issue of the underlying catalog and follows your proposal:
> 
> > Well, concerning these links I think it would be great to have their "title" as the name of the link
> 
> And the link in the catalog is broken, that needs to be fixed by GEE: https://earthengine-stac.storage.googleapis.com/catalog/LANDSAT/LANDSAT_LT04_C01_T1_TOA.json
> 
> cc @simonff

Thank you, looking

**Comment by simonff** [comment]
Thank you, the broken link is fixed.
