### ISSUE TITLE
eo:bands header rendering

### ISSUE THREAD

**Issue by sbrunato** [radiantearth/stac-browser#63]
Hello,
`eo:bands` header is not rendering properly, as you can see when browsing https://tamn.snapplanet.io/collections/S2 through https://stacindex.org/catalogs/sentinel-2-and-landsat-8-catalog . HTML code is displayed in the header:
![image](https://user-images.githubusercontent.com/61419125/104042194-743ff100-51da-11eb-9345-d4e6ff278471.png)

Also another screenshot from the latest stac-browser version running locally:
![image](https://user-images.githubusercontent.com/61419125/104042361-b5d09c00-51da-11eb-877e-87992898a04b.png)

Part of the JSON code from collection or item:
```json
"properties":{
  "eo:bands":[
    {"center_wavelength":0.4439,"common_name":"coastal","full_width_half_max":0.027,"gsd":60,"name":"B01"},
    {"center_wavelength":0.4966,"common_name":"blue","full_width_half_max":0.098,"gsd":10,"name":"B02"},
```

**Comment by m-mohr** [comment]
You are reporting the HTML code in the header, right? I'll take care of it soon for sure, no timeline though. For now, you can remove the HTML code yourself from the common.js file.

By the way, eo:bands in properties is deprecated and will be removed at some point. Better put it into summaries.

**Comment by sbrunato** [comment]
yes, I report the HTML code in the header. Thanks for the tip of putting bands info into summaries, I'll look at it

**Comment by sbrunato** [comment]
I see that in https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l1c/ `eo:bands` are not in `summaries` but:
- in `item_assets.overview` at collection level
- in `assets.overview` at item level

Would you then better recommend to put `eo:bands` in `summaries` or in `[items_]assets.overview` ?

**Comment by m-mohr** [comment]
Depends. ;-) In general, I'd recommend putting them in Items and Collections.

Collections give an overview of the items, so it's helpful for people that don't need to look into individual items to figure out available bands. There it's always a good idea to populate summaries for tools like STAC Index. Items should also give bands so that it's clear which item and/or asset consists of which bands.

Whether to put bands in assets or item properties depends on how your data is structured. For example, if you have several assets with different combinations of bands (or each asset is a band), better put bands in assets. Otherwise put them in item properties. 

If you populate item_assets in collections and you have bands in assets, you can also give them there to give users a better understanding on how your assets are stored. 

Yes, there's some duplication (in Collections), but it helps people to figure out what your items offer as the collection often is the starting point.

**Comment by m-mohr** [comment]
This bug has been fixed by removing the HTML. I don't see a good way with the current table component to add HTML to the headers thus I've removed it for now.

**Comment by m-mohr** [comment]
Re-opened for 2.0.0 as I've figured out there's a headerAbbr option in the v-table component, which we can use in the future.

**Comment by m-mohr** [comment]
This is obsolete in STAC Browser v3
