### ISSUE TITLE
Collections in catalog are listed as child catalogs

### ISSUE THREAD

**Issue by ashleysommer** [radiantearth/stac-browser#84]
See this example -
http://stac-browser-118-138-246-182.nip.io:8081/

All of the Collections are shown under the "Catalogs" tab, not under "Collections".
I know collections are essentially catalogs with extra metadata, but I expected to see them in the "collections" tab.

Is there something wrong with the way I generated the collections? I used pystac v1.0.0rc2 to generate the catalog and collections.

**Comment by m-mohr** [comment]
Yes, actually expected behavior. The tabs are a bit misleading. We can't detect reliably upfront (without reading the files) whether something is a collection or catalog, so everything linked to with rel=child will be a catalog. Collections can only be populated via the API Collections (rel=items). This will change in STAC Browser 3, where we won't distinguish between those two cases any longer.
